### ISSUE TITLE
Waka stop working

### ISSUE THREAD

**Issue by TeodorKolev** [wakatime/eclipse-wakatime#10]
Today waka time stop working on eclipse I have been using a month and today is not working... Any suggestions? server error 500 in log

**Comment by alanhamlett** [comment]
It's fixed now and your logged time should appear after it syncs to the server.

**Comment by TeodorKolev** [comment]
My logged time for yesterday did not appears, can that be fixed?

**Comment by alanhamlett** [comment]
Have you coded inside Eclipse today? The plugin can only sync activity when you're coding, because it doesn't run otherwise. You can also check your `~/.wakatime.db` file with `sqlite3 ~/.wakatime.db` and check if the heartbeats table contains any offline heartbeats waiting to be sent.

**Comment by TeodorKolev** [comment]
yes, I have work today, but at site my history for yesterday is none

**Comment by alanhamlett** [comment]
Hmm, that shouldn't happen with the latest plugin version. What version of the plugin is installed in your Eclipse?

**Comment by TeodorKolev** [comment]
2.5
