### ISSUE TITLE
Appcellerator Studio, no place to add the Key

### ISSUE THREAD

**Issue by fstrazzante** [wakatime/eclipse-wakatime#15]
I'm using Appcelerator Studio which is based on Eclipse. I installed wakatime plugin as I found on this documentation but I couldn't find the place to put the API Key. (I couldn't find WakaTime on the File menu) Where should I add it? Directly on files or something else?!

**Comment by alanhamlett** [comment]
Did you restart Appcelerator Studio? If after restarting there is no `File -> WakaTime API Key` menu then the plugin isn't installed or starting correctly. Do you have any errors in your Error Log window?

**Comment by fstrazzante** [comment]
I reinstalled several times, and after a restart i could find that label. Now I put the KEY and I it's tracking. Thanks.

**Comment by alanhamlett** [comment]
Awesome!
