### ISSUE TITLE
Where to Enter API key

### ISSUE THREAD

**Issue by prakashn27** [wakatime/eclipse-wakatime#17]
I am not getting an pop up or text box to enter API Key. It got installed in eclipse Neon without any issues.

**Comment by alanhamlett** [comment]
Is there a File -> WakaTime API Key menu?

**Comment by prakashn27** [comment]
that actuallhy works. Thanks. Please include that in documentation. +1

**Comment by ethanparker** [comment]
How about for Xcode?

**Comment by alanhamlett** [comment]
@ethanparker It's the same for Xcode.

Here's more info about how to enter your api key:
https://wakatime.com/faq#change-api-key
