### ISSUE TITLE
Waka thinks all XML is HTML

### ISSUE THREAD

**Issue by kferrone** [wakatime/eclipse-wakatime#20]
My dashboard said I had 73% of all my coding so far has been HTML. In reality it should be maybe 1% because I only edited one HTML file while using Waka time so far. Most of my time since I've been using Waka time has been in an ANT file (XML) that I've been working on. Waka time should be better at determining XML versus HTML.

**Comment by alanhamlett** [comment]
Fixed server-side. Thanks!
