### ISSUE TITLE
Error installing 3.0.3, Unable to load repository

### ISSUE THREAD

**Issue by conedmiro** [wakatime/eclipse-wakatime#21]
> Unable to read repository at https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/content.xml.

As seen by the attached image, the ../update-site/ link fails to be seen by Java EE IDE for Web Developers.

For some reason it resolves to ../update-site/content.xml after the attempt to add it

![wakarepo](https://user-images.githubusercontent.com/25594419/27188595-96b442e4-51bc-11e7-83de-6771ab3abf81.png)

**Comment by alanhamlett** [comment]
The update-site protocol says it will check for a file named `content.xml` at the update-site url. It should use `site.xml` when `content.xml` isn't found. If you click `OK` does it still install?

**Comment by bennyty** [comment]
@alanhamlett Same steps, same error for me. No, clicking `OK` doesn't cause it to continue.

**Comment by alanhamlett** [comment]
Just added a `content.xml` file and updated the install instructions:

https://github.com/wakatime/eclipse-wakatime#installation

Does the plugin install correctly now?

**Comment by praszuk** [comment]
Hi i had similar error "Unable to load repository at ... content.xml" on Ubuntu. I couldn't install Wakatime from Marketplace too.
The solution for me was install `ca-certificates-java` in system. Probably when i was upgrading from 14.04 to 16.04 Ubuntu removed it and i couldn't install almost any plugin. 

Now everything works perfectly on Ubuntu 16.04.

**Comment by alanhamlett** [comment]
Just tested with latest version of Eclipse 2019-06 and coding activity is displaying on dashboard. Make sure to install via Eclipse Marketplace under `Help` menu inside Eclipse. Let me know if this is still an issue, otherwise closing for now.
