### ISSUE TITLE
Server returned lastModified <= 0 for https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/artifacts.jar

### ISSUE THREAD

**Issue by mogarick** [wakatime/eclipse-wakatime#22]
I'm getting the mentioned error while trying to install the plugin with Eclipse Oxygen (Version: Oxygen.1a Release (4.7.1a)).
I'm using OSX El Capitan (10.11.6) and I have Xcode installed (version 8.2.1).
I tried installing both via Marketplace and via Install New Software.

**Comment by alanhamlett** [comment]
Does the plugin finish installing even with this error message? You can check by looking for a File -> WakaTime menu inside Eclipse.

**Comment by mogarick** [comment]
No. The option doesn’t appear. 
While trying to install it appears Eclipse tries hard to get the install files but after a while it shows the components that it will install and the weird thing is it says it’s 0 bytes. 
After that I continue and then Eclipse says it needs to restart for
The changes to apply. After that there’s no option for wakatine in the File menu. I then went to the log view an saw the error mentioned.

**Comment by alanhamlett** [comment]
It's normal to see a warning-level message about `lastModified <= 0` for both `content.jar` and `artifacts.jar`, but the installation still finishes for me. I tested on OS X High Sierra (10.13.1) with Eclipse Oxygen (4.7.1a).

Can you try [installing again](https://wakatime.com/eclipse) and see if there are other error messages?

**Comment by mogarick** [comment]
It worked only in a fresh Eclipse install. So it may be conflicting with some other plugin I have installed. I'll try to remove one by one I get back here to report.
Thank you for the attention :)

**Comment by alanhamlett** [comment]
Thanks for the update, I'll close this for now since it's working.
