### ISSUE TITLE
Wakatime is installed but not working

### ISSUE THREAD

**Issue by Manerr** [wakatime/eclipse-wakatime#23]
Wakatime is installed but not working
![wakatime](https://user-images.githubusercontent.com/1338257/34456674-f2e72104-ed9c-11e7-8ea1-9bcc8f8a75a3.jpg)
I don't have the Wakatime button, for the API key
![wakatime2](https://user-images.githubusercontent.com/1338257/34456677-0eae5786-ed9d-11e7-91d3-c1fb3a2f4dd6.jpg)
Eclipse version: 
![eclipseversion](https://user-images.githubusercontent.com/1338257/34456681-21ff92a0-ed9d-11e7-918c-c7279e4b08c7.jpg)

**Comment by alanhamlett** [comment]
Can you restart Eclipse and if the WakaTime menu is not available then try re-installing the plugin?

**Comment by Manerr** [comment]
I have already tried to relaunch eclipse and reinstall the plugin

**Comment by Manerr** [comment]
I reinstalled eclipse and it works
