### ISSUE TITLE
No time logged from Eclipse Oxygen

### ISSUE THREAD

**Issue by rdcoe** [wakatime/eclipse-wakatime#25]
I installed wakatime and installed my API key.  Confirmed the key in eclipse matches the .wakatime.cfg key as well as the key in my wakatime profile.

Eclipse installation details:
!ENTRY com.wakatime.eclipse.plugin 4 0 2018-02-17 15:18:50.674
!MESSAGE Could not find python binary.

!ENTRY com.wakatime.eclipse.plugin 1 0 2018-02-17 15:18:54.673
!MESSAGE Downloading and installing wakatime-cli ...

!ENTRY com.wakatime.eclipse.plugin 1 0 2018-02-17 15:19:01.501
!MESSAGE Finished downloading and installing wakatime-cli.

!ENTRY org.eclipse.equinox.p2.repository 2 0 2018-02-17 15:58:49.672
!MESSAGE Server returned lastModified <= 0 for https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/content.jar

I see several "...lastModified <=0 ..." messages but no obvious stacktraces.  I have restart eclipse several times.

**Comment by alanhamlett** [comment]
Can you turn on Debug mode, then check Eclipse's Error Log window and also `~/.wakatime.log` if it exists? To turn on debug mode, add a `debug=true` line to your `~/.wakatime.cfg` file:
https://github.com/wakatime/wakatime#troubleshooting

After turning on debug mode, restart Eclipse and type anything in a file. Watch `~/.wakatime.log` and your Eclipse Error Log window for any output and also check your [Plugin Status](https://wakatime.com/plugins/status) on WakaTime to see if we've received coding activity from your typing.

**Comment by alanhamlett** [comment]
Just tested with latest version of Eclipse 2019-06 and coding activity is displaying on dashboard. Please let me know if this is still an issue, otherwise closing for now.
