### ISSUE TITLE
Not compatible with new Eclipse 06-2019

### ISSUE THREAD

**Issue by ghobashy** [wakatime/eclipse-wakatime#29]
I just installed new Eclipse Neon 3, and Waka is not compatible with it.

![image](https://user-images.githubusercontent.com/7414889/60757907-f7deb780-a010-11e9-8b37-c1a61d47c866.png)

any workarounds?

**Comment by alanhamlett** [comment]
Just updated the solution in Eclipse Marketplace adding support for 2019-06. Can you search the marketplace for `wakatime` and try installing again?

**Comment by ghobashy** [comment]
Works like charm!! thanks for your fast response.
