### ISSUE TITLE
Installation issue: Missing requirements wakatime 3.0.3

### ISSUE THREAD

**Issue by NirmalSilwal** [wakatime/eclipse-wakatime#32]
Cannot complete the install because one or more required items could not be found.
  Software being installed: WakaTime 3.0.3 (com.wakatime.eclipse.feature.feature.group 3.0.3)
  Missing requirement: WakaTime 3.0.3 (com.wakatime.eclipse.plugin 3.0.3) requires 'bundle org.apache.httpcomponents.httpclient 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: WakaTime 3.0.3 (com.wakatime.eclipse.feature.feature.group 3.0.3)
    To: com.wakatime.eclipse.plugin [3.0.3]
![wakatime](https://user-images.githubusercontent.com/31946761/89595905-77256700-d873-11ea-9a77-e8f7b3de1acc.PNG)

**Comment by NirmalSilwal** [comment]
https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/

this URL itself is invalid as defined in https://wakatime.com/eclipse#install-old 
400: Invalid request

**Comment by alanhamlett** [comment]
Both those urls are valid, must be that you're behind a proxy. Try installing from a different ISP?

**Comment by NirmalSilwal** [comment]
I tried using VPN, didn't work. This URL is not working. [https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/](https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/)

**Comment by alanhamlett** [comment]
Eclipse doesn't need https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/ to work since Eclipse only looks for https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/site.xml at the update site url. Sorry I wasn't clear about that. Does the site.xml link work without VPN?

**Comment by NirmalSilwal** [comment]
Yes, site.xml works without VPN.

**Comment by alanhamlett** [comment]
Does the install work via marketplace instead of using the old site url method? I've just tested both install methods today and they work on my eclipse v4.18.0.
