### ISSUE TITLE
Needs python installed warning

### ISSUE THREAD

**Issue by lyctw** [wakatime/eclipse-wakatime#34]
I've installed python in my system and there is no error in `.wakatime.log`.

Warning after restart.

![Screenshot from 2021-01-25 10-38-47](https://user-images.githubusercontent.com/12937401/105654735-95525280-5ef9-11eb-8b96-4df1aeb27925.png)

My eclipse version:

![Screenshot from 2021-01-25 10-40-05](https://user-images.githubusercontent.com/12937401/105654818-c16dd380-5ef9-11eb-8d3c-6ecc42647fb6.png)

My `python` command is aliased to Python 3.8

**Comment by redneterp** [comment]
Workaround 
`cd /usr/bin`
`sudo ln -s python3 python`

Notice the /usr/bin folder. If you are using alias the plugin won't find it.

https://github.com/wakatime/eclipse-wakatime/blob/efec7a09edcd1d25d2de31032f8a9a15a146c771/com.wakatime.eclipse.plugin/src/com/wakatime/eclipse/plugin/Dependencies.java#L60

**Comment by alanhamlett** [comment]
Fixed in v4.0.0 by removing dependency on Python.
