### ISSUE TITLE
'No software site found' when installed the plugin 

### ISSUE THREAD

**Issue by Zeroto521** [wakatime/eclipse-wakatime#35]
I followed the guide to install the waketime plugin. But I found that problem.

![image](https://user-images.githubusercontent.com/25895405/110405641-d5d9ea00-80bb-11eb-9df5-49b997ccfee6.png)

So I opened https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/ in the browser.

The response showed that `404: Not Found`.

**Comment by alanhamlett** [comment]
Fixed in v4.0.0.
