### ISSUE TITLE
Connection timeout while updating wakatime-cli causes eclipse to freeze

### ISSUE THREAD

**Issue by ZimoLoveShuang** [wakatime/eclipse-wakatime#36]
In some areas, the upgrade mechanism of plugin will causes eclipse to jam. Here is the log:
`!ENTRY com.wakatime.eclipse.plugin 2 0 2021-04-12 18:47:28.677
!MESSAGE Warning
!STACK 0
java.net.ConnectException: Connection timed out: connect`

Using asynchronous network update plug-in may be a solution, hope to adopt. And repair as soon as possible. Thank you

**Comment by alanhamlett** [comment]
Fixed in v4.0.0.
