### ISSUE TITLE
How install on DBeaver 22.1.0?

### ISSUE THREAD

**Issue by moeshin** [wakatime/eclipse-wakatime#40]
via: https://wakatime.com/dbeaver

No `DBeaver Marketplace`

![image](https://user-images.githubusercontent.com/28248888/175778873-aeb4ad85-61f5-4359-b9c5-76831690f4e9.png)

And could not found https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/

![image](https://user-images.githubusercontent.com/28248888/175778917-61207894-c02e-47d5-9177-9171ed6ebd3a.png)

**Comment by alanhamlett** [comment]
Normally when using update site `https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/` it should find the `site.xml` file at that folder. What happens when you select `No` and try to continue with the installation?

**Comment by moeshin** [comment]
Cannot next:

![image](https://user-images.githubusercontent.com/28248888/175782890-36a2c3c6-1faf-4f8d-b155-2c8a926f1ce4.png)

**Comment by alanhamlett** [comment]
Try clicking `Add...`? It works for me:

<img width="948" alt="Screen Shot 2022-06-25 at 2 27 24 PM" src="https://user-images.githubusercontent.com/522344/175784290-7ec584f5-1f48-4211-9309-c8b5eb76a039.png">

**Comment by moeshin** [comment]
![dbeaver_N9BP67OGn3](https://user-images.githubusercontent.com/28248888/175785294-55abf2a2-ce78-4738-806c-0c7ebe35a48c.gif)

**Comment by moeshin** [comment]
I configured the system proxy or set the proxy in `Preferences > Network Connections` but it didn't apply.
Now I clone this repository to local and click `Add.. > Local...` to import this local repository.

**Comment by alanhamlett** [comment]
Ah, so it's a proxy issue with the `Install New Software...` feature?

**Comment by moeshin** [comment]
Yes.
