### ISSUE TITLE
Dbeaver don't show options

### ISSUE THREAD

**Issue by Phosphorus-M** [wakatime/eclipse-wakatime#41]
In the most recent versions of DBeaver the plugin is not showing the option to insert the API key
I don't know how to solve it, someone happens or it's just to me?

**Comment by benyaminl** [comment]
File > Wakatime > Insert API Key, it's there

**Comment by alanhamlett** [comment]
It won't ask if your api key has already been entered previously. You can find it from the File -> WakaTime menu to change it.
