### ISSUE TITLE
DBeaver log time spent in DB properties, data, diagram

### ISSUE THREAD

**Issue by pire** [wakatime/eclipse-wakatime#44]
At the moment it only tracks time spent in the query editor.

Unsure if this is possible, but would be amazing if the plugin could also track the time spent in the other database views Properties, Data, ER Diagram.

**Comment by benyaminl** [comment]
@pire hello, I want to know, are you using eclipse + Dbeaver or only dbeaver client?

My activity in the editor doesn't work at all tbh :/ it doesn't track any query that I write

**Comment by alanhamlett** [comment]
Do those views have an associated filename? There's ways around that by changing the heartbeat type to something other than file, but having a filename is best for project detection, branch detection, and language detection.

**Comment by alanhamlett** [comment]
This line might be preventing it from tracking Diagrams:

https://github.com/wakatime/eclipse-wakatime/blob/1c11b623e1b94d28c734558f13cdada91badeb3c/com.wakatime.eclipse.plugin/src/com/wakatime/eclipse/plugin/WakaTime.java#L143

**Comment by pire** [comment]
I aaaaaaaaaaaaaaaaaaaaaaam clueless about .java!

Would this be something I can find locally, change and try out for you without building the plugin?

Am on MacOS Monterey 12.6

**Comment by alanhamlett** [comment]
Added support for DBeaver properties, diagrams, and other editor types with 66888a07db5afe7397943b86d4d99bf1fbb0c80f.
