### ISSUE TITLE
Feature request: DBeaver customise project name used in dashboard

### ISSUE THREAD

**Issue by pire** [wakatime/eclipse-wakatime#45]
At the moment it only tracks time spent in the query editor. In the Wakatime dashboard these are shown as _Script-X.sql_ and belong to a _General_ project.

The ability to set a custom name or even default to a database + table names combo for the project name would make it much easier to be able to track time across different projects.

**Comment by pire** [comment]
Actually, digging around for another issue I noticed that this is already my case - I just need to separate my connections into different projects, rather than using the default General project!

**Comment by alanhamlett** [comment]
Improved support for DBeaver properties, diagrams, and other editor types with 66888a07db5afe7397943b86d4d99bf1fbb0c80f.
