### ISSUE TITLE
dbeaver is failed while install plugin

### ISSUE THREAD

**Issue by chartm17** [wakatime/eclipse-wakatime#48]
![image](https://github.com/wakatime/eclipse-wakatime/assets/147707546/3d654095-6c3c-40e9-98a9-58902a509b75)

**Comment by alanhamlett** [comment]
I can't reproduce this. Could it be a network issue? Are you able to connect to GitHub without a proxy?

**Comment by alanhamlett** [comment]
Try using these new install instructions:

https://wakatime.com/dbeaver

**Comment by moeshin** [comment]
> Try using these new install instructions:
> 
> https://wakatime.com/dbeaver

New install url `https://wakatime.com/eclipse/update-site/` install failed.

HTTP `http://wakatime.com/eclipse/update-site/` same error.

![image](https://github.com/wakatime/eclipse-wakatime/assets/28248888/ebb341f8-de82-4126-8724-a994d8baccb2)

--------

I found my DBeaver 24.0.0 unsupport some HTTPS, already trusted that.

![image](https://github.com/wakatime/eclipse-wakatime/assets/28248888/6e38c69b-4721-4fb0-850f-8128be6c0446)

Now i can use HTTP `http://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/` install it.

**Comment by uniform641** [comment]
Same error on DBeaver Linux (Version 24.2.3.202410221007).
I tried `http://wakatime.com/eclipse/update-site/`, `https://wakatime.com/eclipse/update-site/`, `http://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/`, `https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/`. None of them worked.

![image](https://github.com/user-attachments/assets/52425268-e1bf-4598-8f36-364fd1595d06)
![image](https://github.com/user-attachments/assets/d9bf1046-349a-486e-9886-8ad472644a26)
