### ISSUE TITLE
Installation Error - Missing dependancy

### ISSUE THREAD

**Issue by bencellis** [wakatime/eclipse-wakatime#5]
Following instructions  for installation in Eclipse on Ubuntu and getting the following:

Cannot complete the install because one or more required items could not be found.
  Software being installed: WakaTime 2.0.4 (com.wakatime.eclipse.feature.feature.group 2.0.4)
  Missing requirement: WakaTime 2.0.4 (com.wakatime.eclipse.plugin 2.0.4) requires 'bundle org.apache.httpcomponents.httpclient 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: WakaTime 2.0.4 (com.wakatime.eclipse.feature.feature.group 2.0.4)
    To: com.wakatime.eclipse.plugin [2.0.4]

**Comment by LeoDutra** [comment]
Happens to me too on IBM Rational Application Developer 8.5 (Eclipse 3.6).

**Comment by LeoDutra** [comment]
org.apache.httpcomponents.httpcore is required on some error messages too.

Maybe plugin should add those ones to dependency.

**Comment by LeoDutra** [comment]
Try to update Eclipse. Worked for me on IBM Rational Application Developer 8.5 (reference: issue  https://github.com/wakatime/eclipse-wakatime/issues/6)

**Comment by alanhamlett** [comment]
`org.apache.httpcomponents.httpcore` is already required as a dependency:

[META-INF/MANIFEST.MF](https://github.com/wakatime/eclipse-wakatime/blob/c02685afd59762db69d587db0ea9d53ef561cc55/com.wakatime.eclipse.plugin/META-INF/MANIFEST.MF#L13)

**Comment by LeoDutra** [comment]
MUST be Eclipse.

**Comment by LeoDutra** [comment]
You can try to download the httpcomponents, extract on `eclipse/plugins` and rename it to the missing bundle.

Worked for me a time ago.

**Comment by italks** [comment]
the same to me，i can't install wakatime in my eclipse

**Comment by marekkaczkowski** [comment]
+1

**Comment by ihwf** [comment]
+1

**Comment by alanhamlett** [comment]
Closing as this is 3 years old. If it's still an issue, leave a comment and I'll reopen it.
