### ISSUE TITLE
Not working with linux eclipse

### ISSUE THREAD

**Issue by codex8** [wakatime/eclipse-wakatime#8]
Hey..  
   i've installed eclipse mars for php and wakatime eclipse plugin and also setup API key My OS is linux mint 64bit but it's not working. It's working good with netbeans in same the machine.

**Comment by codex8** [comment]
i just found something my project name is web.aptronindia in eclipse and but wakatime analytics shows files in unknow project . what should i do ?

**Comment by alanhamlett** [comment]
@codex8 just to clarify, it's logging time but in the wrong project (Unknown Project)?

The easiest way to log the correct project is run `git init` inside your project folder. It should have picked up the project from Eclipse, unless you've got an old [wakatime cli](https://github.com/wakatime/wakatime) version.

**Comment by codex8** [comment]
thanks @alanhamlett
