### ISSUE TITLE
Changes are not written to file 

### ISSUE THREAD

**Issue by rice2007** [wakatime/eclipse-wakatime#9]
On clean install, the error log says `pythonw: can't open file 'C:\SA-IDE\sts-3.4.0\configuration\org.eclipse.osgi\bundles\1078\1\.cp\dependencies\wakatime-master\wakatime\cli.py': [Errno 2] No such file or directory`. The directory ends at `dependencies`.

I manually created the `cli.py` file in the above directory. The error log says that `pythonw` returned 0, but the `cli.py` file never gets updated. The log file does not have any entries for Eclipse changes, but all of my Sublime Text changes are logged. The default version of Python is 3.4.3, but 2.7 is also installed.

Python 2 and 3. Windows 7 x64. Eclipse 3.4.0 (Spring Toolsuite).

**Comment by alanhamlett** [comment]
Can you delete the folder `C:\SA-IDE\sts-3.4.0\configuration\org.eclipse.osgi\bundles\1078\1\.cp\dependencies\wakatime-master` then re-open Eclipse? It should re-download that folder from GitHub since looks like it was corrupted when downloading/extracting.

**Comment by rice2007** [comment]
I didn't realize there was an entire directory was missing. Reopening Eclipse still gave an unknown hosts error. I manually downloaded and extracted the archive into the directory, and this fixed the issue. Thanks!
